### ISSUE TITLE
XP bands seem to be RETAIL value

### ISSUE THREAD

**Issue by Besbe** [Besbe/Topaz-Next#3]
- [] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

That's what Simseru says....

**Comment by Simseru** [comment]
Buff duration was 12hours instead of 3 and used at lvl 1 and still active now at lvl 10.
