### ISSUE TITLE
R/E Nation Rings

### ISSUE THREAD

**Issue by Simseru** [Besbe/Topaz-Next#4]
- [] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

R/E Nation rings are mailable between chars. While this is a new feature it may be OOE and not wanted on this server.

**Comment by Besbe** [comment]
Fixed on 0475fd7ff7d83b6a896d5f92b79dd48dbfc9c90c
